### PR TITLE
Update functional_tests.py

### PR DESCRIPTION
**Pull request by PresidentNick**
added a test case and changed the error code on testBadRequestOne

### CODE REVIEW

**Comment by taylorkline** [comment]
Hi presidentnick. I will accept testBadRequestThree but please leave 404 for testBadRequestOne

**Comment by PresidentNick** [comment]
I changed it back, although the professor said either is fine :P

**Comment by taylorkline** [comment]
You could assert either are okay like in the test with 200 or 204, or I can accept as is.

**Comment by PresidentNick** [comment]
done

**Comment by taylorkline** [comment]
Can you please make sure my code passes all these tests since the update?

**Comment by taylorkline** [comment]
Thanks :D

**Comment by PresidentNick** [comment]
You're welcome :+1:

**Pull request merged**
